# Appointment.create(service_name: "Classic Manicure", date: Date.today)
# Appointment.create(service_name: "Spa Manicure", date: Date.today)
# Appointment.create(service_name: "Classic Pedicure", date: Date.today)
# Appointment.create(service_name: "Spa Pedicure", date: Date.today)
# Appointment.create(service_name: "Gel Manicure", date: Date.today)
# Appointment.create(service_name: "Gel Pedicure", date: Date.today)
# Appointment.create(service_name: "Mini Manicure", date: Date.today)
# Appointment.create(service_name: "Mini Pedicure", date: Date.today)